### ISSUE TITLE
pairwise log2 comparisons

### ISSUE THREAD

**Issue by will-NYGC** [kcakdemir/HiCPlotter#7] opened 2016-06-17 20:42 UTC
Hi Kadir,

I'm trying to use the pairwise comparisons function "-p 1 -c 1" but the plots I get don't have any negative values. Weirdly when I plot log2(A/B) it is not the inverse of the log2(B/A) plot.

![astro vs neu-chr1 ofbins 1-200 500k](https://cloud.githubusercontent.com/assets/4604217/16164036/7ed53cda-34aa-11e6-948f-d408fa4ee94e.png)
The top left log2 plot and the one immediately to its right are inverses but don't appear that way. Any ideas what's going on?

-will

**Comment by kcakdemir** [comment] 2016-06-17 22:20
Hey Will,

Do you mind running it with -cs -10,10?

Current version converts the values between a certain range (default:0,2), after log2 comparison, to 1 so the maps wont look super busy but it seems it doesnt work as intended. 
Please let me know how it goes, so I will either remove that part or change the default values....

**Comment by kcakdemir** [comment] 2016-06-29 19:44
Hey Will,

Did -cs parameter usage work for you? I will close this issue if you think it works better now? (I changed the default behavior so it doenst assign any values to 1 anymore)

**Comment by will-NYGC** [comment] 2016-06-30 15:19
Hi Kadir, sorry lost track of this but just tested and it with this command:
```
python2.7 ~/tools/HiCPlotter/HiCPlotter.py -tri 1 -bed ../../analysis/hic_results/matrix/Sample_2607Astro/raw/100000/*abs.bed -f ../../analysis/hic_results/matrix/Sample_2607Astro/iced/100000/Sample_2607Astro_100000_iced.matrix ../../analysis/hic_results/matrix/Sample_2607Neu/iced/100000/Sample_2607Neu_100000_iced.matrix -n Astro Neu -chr chr1 -o TEST -p 1 -c 1 -cs 0,0
```
and still doesn't work.
![test-chr1 ofbins 0-2492 100k](https://cloud.githubusercontent.com/assets/4604217/16493694/625fe046-3eb4-11e6-8516-4720a7cef412.png)

**Comment by kcakdemir** [comment] 2016-06-30 16:19
Thanks for the example Will! Something is not right here, I will check again and let you know...

**Comment by sf-nevermore** [comment] 2016-11-01 22:22
I think the problem is when doing matrix1/matrix2. For some reason, probably because type of matrix, the quotients in range 0 to 1 are rounded to 0. So all the blue point (log2 value of 0-1) is change to -inf and result in white in the plot. I do small modification of it: matrix2/(matrix1*1.0) then it seems work now.

![image](https://cloud.githubusercontent.com/assets/7236497/19909809/88e5c62e-a046-11e6-9a67-0273c771a994.png)

**Comment by kcakdemir** [comment] 2016-11-01 22:40
Good point, thanks!! Any quick way to determine when the majority of the quotients are [0,1] so using your trick would be good? For Will's data, it looks okay for 553Astro/2607Neu but the other way around is having this issue...

**Comment by sf-nevermore** [comment] 2016-11-01 22:51
I think all Will's data did not show any blue area (negative dots). So did mine. The matrix1 and matrix2 are set to int type. So when it does divide it will result in int type not float points. Times 1.0 just change one matrix to floating points so that it will not round to 0. So I think changing it to floating points is required to every dataset of the comparison mode.

**Comment by kcakdemir** [comment] 2016-11-01 22:58
I agree! Just updated the code for float conversions, please let me know if you notice any issues...

**Comment by will-NYGC** [comment] 2016-11-02 14:08
thanks guys, I'll update and test this week.

**Comment by kcakdemir** [comment] 2016-12-12 18:13
guys, i'm going to close this issue as I assume it's mostly resolved? Please re-open it, if need be.
happy holidays!!

**Closed by kcakdemir** 2016-12-12 18:13 UTC

**Comment by will-NYGC** [comment] 2016-12-12 18:14
sorry didn't follow up with results but everything is working now. thanks! happy holidays.
